package com.qijukeji.entityModel;

/**
 * 活动实体对象
 * generated by system on Apr 27, 2017 5:23:28 PM
 */
public class ActivityEM {


    /**
     * 唯一ID
     * @return
     */
    private String uuid;


    /**
     * 标题
     */
    private String title;


    /**
     * 描述
     */
    private String description;


    /**
     * 类型
     */
    private String type;


    /**
     * 活动地址
     */
    private String address;


    /**
     * 封面图片
     */
    private String coverImage;


    /**
     * 开始时间
     */
    private String startTime;


    /**
     * 结束时间
     */
    private String endTime;


    /**
     * 价格
     */
    private Double price = 0.0;


    /**
     * 活动内容id
     */
    private String contentID;


    /**
     * 下限人数
     */
    private Integer lowerLimit = 0;


    /**
     * 上限人数
     */
    private Integer upperLimit;


    /**
     * 开始领取时间
     */
    private String startGetTime;


    /**
     * 结束领取时间
     */
    private String endGetTime;


    /**
     * 开始展示时间
     */
    private String startShowTime;


    /**
     * 结束展示时间
     */
    private String endShowTime;


    /**
     * 是否展示
     */
    private Boolean showEnable;


    /**
     * 浏览次数
     */
    private Integer viewCount = 0;


    /**
     * 获取次数
     */
    private Integer getCount = 0;


    /**
     * 领取限制
     */
    private Boolean isGetLimitRequired = false;


    /**
     * 持续时间
     */
    private Integer durationDay;


    /**
     * 分享图片
     */
    private String shareImage;


    /**
     * 创建时间
     */
    private String createdTime;

    /**
     * 更新时间
     */
    private String updatedTime;




    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCoverImage() {
        return coverImage;
    }

    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getContentID() {
        return contentID;
    }

    public void setContentID(String contentID) {
        this.contentID = contentID;
    }

    public Integer getLowerLimit() {
        return lowerLimit;
    }

    public void setLowerLimit(Integer lowerLimit) {
        this.lowerLimit = lowerLimit;
    }

    public Integer getUpperLimit() {
        return upperLimit;
    }

    public void setUpperLimit(Integer upperLimit) {
        this.upperLimit = upperLimit;
    }

    public String getStartGetTime() {
        return startGetTime;
    }

    public void setStartGetTime(String startGetTime) {
        this.startGetTime = startGetTime;
    }

    public String getEndGetTime() {
        return endGetTime;
    }

    public void setEndGetTime(String endGetTime) {
        this.endGetTime = endGetTime;
    }

    public String getStartShowTime() {
        return startShowTime;
    }

    public void setStartShowTime(String startShowTime) {
        this.startShowTime = startShowTime;
    }

    public String getEndShowTime() {
        return endShowTime;
    }

    public void setEndShowTime(String endShowTime) {
        this.endShowTime = endShowTime;
    }

    public Boolean getShowEnable() {
        return showEnable;
    }

    public void setShowEnable(Boolean showEnable) {
        this.showEnable = showEnable;
    }

    public Integer getViewCount() {
        return viewCount;
    }

    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    public Integer getGetCount() {
        return getCount;
    }

    public void setGetCount(Integer getCount) {
        this.getCount = getCount;
    }

    public Boolean getGetLimitRequired() {
        return isGetLimitRequired;
    }

    public void setGetLimitRequired(Boolean getLimitRequired) {
        isGetLimitRequired = getLimitRequired;
    }

    public Integer getDurationDay() {
        return durationDay;
    }

    public void setDurationDay(Integer durationDay) {
        this.durationDay = durationDay;
    }

    public String getShareImage() {
        return shareImage;
    }

    public void setShareImage(String shareImage) {
        this.shareImage = shareImage;
    }

    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime;
    }

}