package com.qijukeji.entityModel;

import java.util.*;

/**
 * 核查订单实体对象
 * generated by system on Apr 27, 2017 8:53:58 AM
 */
public class CheckOrder {

    private String uuid;
    /**
     * 导购ID
     */
    private String staffID;


    /**
     * 用户ID
     */
    private String userID;

    private String orderNumber;

    /**
     * 用户电话
     */
    private String userPhone;


    /**
     * 用户姓名
     */
    private String userName;


    /**
     * 用户小区
     */
    private String userAddressVillage;


    /**
     * 用户单元
     */
    private String userAddressUnit;


    /**
     * 总金额
     */
    private Double totalMoney = 0.0;


    /**
     * 支付金额
     */
    private Double payMoney = 0.0;


    /**
     * 备注
     */
    private String remark;

    private String source;
    /**
     * 核单状态
     */
    private Integer status = 0;

    private Boolean deleted;

    /**
     * 创建时间
     */
    private Date createdTime;

    /**
     * 更新时间
     */
    private Date updatedTime;

    /**
     * 优惠金额
     */

    private Double discountPrice;


    /**
     * 开始时间
     */
    private String begindateTime;

    /**
     * 结束时间
     */
    private String enddateTime;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getStaffID() {
        return staffID;
    }

    public void setStaffID(String staffID) {
        this.staffID = staffID;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserAddressVillage() {
        return userAddressVillage;
    }

    public void setUserAddressVillage(String userAddressVillage) {
        this.userAddressVillage = userAddressVillage;
    }

    public String getUserAddressUnit() {
        return userAddressUnit;
    }

    public void setUserAddressUnit(String userAddressUnit) {
        this.userAddressUnit = userAddressUnit;
    }

    public Double getTotalMoney() {
        return totalMoney;
    }

    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }

    public Double getPayMoney() {
        return payMoney;
    }

    public void setPayMoney(Double payMoney) {
        this.payMoney = payMoney;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    public Double getDiscountPrice() {
        return discountPrice;
    }

    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    public String getBegindateTime() {
        return begindateTime;
    }

    public void setBegindateTime(String begindateTime) {
        this.begindateTime = begindateTime;
    }

    public String getEnddateTime() {
        return enddateTime;
    }

    public void setEnddateTime(String enddateTime) {
        this.enddateTime = enddateTime;
    }
}