package com.qijukeji.entityModel;

import android.graphics.Bitmap;

/**
 * generated by system on Apr 27, 2017 8:53:58 AM
 */
public class CheckOrder {

    private String uuid;

    private String staffID;

    private String userID;

    private String orderNumber;

    private String userPhone;

    private String userName;

    private String userAddressVillage;

    private String userAddressUnit;

    private Double totalMoney = 0.0;

    private Double payMoney = 0.0;

    private String remark;

    private String source;

    private Integer status = 0;

    private Boolean deleted;

    private String createdTime;

    private String updateTime;

    private Double discountPrice;

    private String begindateTime;

    private String enddateTime;

    private String userHeadImageUrl;

    private String justGift;

    private Bitmap wxHeadpic;

    public CheckOrder(String uuid, String userPhone, String userName, String userAddressVillage, String userAddressUnit, String source, Integer status, String updateTime, Bitmap wxHeadpic, String justGift) {
        this.uuid = uuid;
        this.userPhone = userPhone;
        this.userName = userName;
        this.userAddressVillage = userAddressVillage;
        this.userAddressUnit = userAddressUnit;
        this.source = source;
        this.status = status;
        this.updateTime = updateTime;
        this.wxHeadpic = wxHeadpic;
        this.justGift = justGift;
    }

    public Bitmap getWxHeadpic() {
        return wxHeadpic;
    }

    public void setWxHeadpic(Bitmap wxHeadpic) {
        this.wxHeadpic = wxHeadpic;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getStaffID() {
        return staffID;
    }

    public void setStaffID(String staffID) {
        this.staffID = staffID;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserAddressVillage() {
        return userAddressVillage;
    }

    public void setUserAddressVillage(String userAddressVillage) {
        this.userAddressVillage = userAddressVillage;
    }

    public String getUserAddressUnit() {
        return userAddressUnit;
    }

    public void setUserAddressUnit(String userAddressUnit) {
        this.userAddressUnit = userAddressUnit;
    }

    public Double getTotalMoney() {
        return totalMoney;
    }

    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }

    public Double getPayMoney() {
        return payMoney;
    }

    public void setPayMoney(Double payMoney) {
        this.payMoney = payMoney;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public Double getDiscountPrice() {
        return discountPrice;
    }

    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    public String getBegindateTime() {
        return begindateTime;
    }

    public void setBegindateTime(String begindateTime) {
        this.begindateTime = begindateTime;
    }

    public String getEnddateTime() {
        return enddateTime;
    }

    public void setEnddateTime(String enddateTime) {
        this.enddateTime = enddateTime;
    }

    public String getUserHeadImageUrl() {
        return userHeadImageUrl;
    }

    public void setUserHeadImageUrl(String userHeadImageUrl) {
        this.userHeadImageUrl = userHeadImageUrl;
    }

    public String getJustGift() {
        return justGift;
    }

    public void setJustGift(String justGift) {
        this.justGift = justGift;
    }
}