package com.qijukeji.entityModel;

/**
 * 顾客活动实体对象
 * generated by system on Apr 27, 2017 8:34:04 AM
 */
public class UserActivity {
    private static final long serialVersionUID = 1L;
    /**
     * 唯一ID
     */
    private String uuid;

    /**
     * 活动订单号
     */
    private String ordernumber;

    /**
     * 导购ID
     */
    private String staffid;

    /**
     * 用户ID
     */
    private String userid;

    /**
     * 活动ID
     */
    private String activityid;


    /**
     * 姓名
     */
    private String name;


    /**
     * 电话
     */
    private String phone;


    /**
     * 小区
     */
    private String addressvillage;


    /**
     * 单元
     */
    private String addressunit;

    /**
     * 活动备注
     */
    private String comment;

    /**
     * 活动内容
     */
    private String content;

    @Override
    public String toString() {
        return "UserActivity{" +
                "uuid='" + uuid + '\'' +
                ", ordernumber='" + ordernumber + '\'' +
                ", staffid='" + staffid + '\'' +
                ", userid='" + userid + '\'' +
                ", activityid='" + activityid + '\'' +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", addressvillage='" + addressvillage + '\'' +
                ", addressunit='" + addressunit + '\'' +
                ", comment='" + comment + '\'' +
                ", content='" + content + '\'' +
                '}';
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getOrdernumber() {
        return ordernumber;
    }

    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber;
    }

    public String getStaffid() {
        return staffid;
    }

    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getActivityid() {
        return activityid;
    }

    public void setActivityid(String activityid) {
        this.activityid = activityid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddressvillage() {
        return addressvillage;
    }

    public void setAddressvillage(String addressvillage) {
        this.addressvillage = addressvillage;
    }

    public String getAddressunit() {
        return addressunit;
    }

    public void setAddressunit(String addressunit) {
        this.addressunit = addressunit;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}