package com.qijukeji.entityModel;

/**
 * 品牌创建Command
 * generated by system on Apr 25, 2017 9:51:57 AM
 */
public class BrandCreateCommand {
    private static final long serialVersionUID = 1L;
    /**
     * 名称
     */
    private String name;

    /**
     * 描述
     */
    private String description;

    /**
     * 标志
     */
    private String logo;

    /**
     * 口号
     */
    private String slogon;


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getSlogon() {
        return slogon;
    }

    public void setSlogon(String slogon) {
        this.slogon = slogon;
    }

    @Override
    public String toString() {
        return "BrandCreateCommand{" +
                "name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", logo='" + logo + '\'' +
                ", slogon='" + slogon + '\'' +
                '}';
    }
}